- R/ui_functions.R
- tests/testthat/test-pip.R
- tests/testthat/test-plumber-ui.R
* Add region_code to /hp-countries endpoint
* Switch to to pcn_region_code in ui_pc_charts, and rename it to
region_code
Closes #36
cc: @tonyfujs
> Add region_code to UI functions

- DESCRIPTION
- R/clean_api_data.R
* Remove dplyr dep
* Remove readr dep
* Move purrr to Suggests
Closes #40.
> Remove dplyr

- inst/plumber/v1/plumber.R
> Add regional aggregates for all years endpoint

- R/clean_api_data.R
- R/rg_pip.R
- R/ui_functions.R
- R/utils.R
- tests/testthat/test-pip.R
* Add mrv filtering to subset_lkup()
* Add "mrv" as an accepted query parameter
* Add some simple unit tests
> Add mrv option for year in pip()

- R/ui_functions.R
- tests/testthat/test-plumber-ui.R
- tests/testthat/test-ui_functions.R
* Convert list of headcounts to data frame for cp-key-indicators
* Add poverty_line column to pov_trend chart response
> Unname response from CP KI endpoint

- R/clean_api_data.R
- R/utils-plumber.R
- inst/plumber/v1/plumber.R
- tests/testthat/test-utils-plumber.R
Allows switching between json, csv and rds.
> Add format as parameter for /pip endpoint

- R/utils-plumber.R
Hi @tonyfujs. I believe this is a minor bug on `check_param_num()`
> Closes #85

- inst/plumber/v1/endpoints.R
> Make sure NAs are returned for /cp-key-indicators

- R/ui_functions.R
> Fix reporting level bug for CP page

- R/utils-plumber.R
> Fix json NA as null

- R/start_api.R
- inst/TMP/TMP_prepare_data.R
- inst/plumber/v1/endpoints.R
- inst/plumber/v1/openapi.yaml
- inst/plumber/v1/plumber.R
Add an endpoint to show the GH SHA1 hash of the wbpip and pipapi pkgs.
@tonyfujs : What about something like this? Could also be incorporated in one of the existing endpoints if you prefer.
> Add /gh-hash endpoint

- .github/workflows/R-CMD-check.yaml
- .github/workflows/pkgdown.yaml
- .github/workflows/pr-commands.yaml
- .github/workflows/test-coverage.yaml
> Update GH workflows

- R/add_agg_stats.R
- man/ui_hp_countries.Rd
This is a hot fix so the function does not throw an error when dealing with data from URY and ARG
> Add except parameter so the add_agg_stats()

- R/utils.R
Hi @tonyfujs This sets the max povline to 10 000 which should solve the GM request. 
Closes #199
> Increase max value for povline

- R/ui_functions.R
- man/ui_cp_key_indicators.Rd
- tests/testthat/test-ui_functions.R
- tests/testthat/test-utils-plumber.R
> Add povline NULL option for cp_key_indicators()

- R/ui_functions.R
- tests/testthat/test-plumber-ui.R
- tests/testthat/test-ui_functions.R
See #149
If we want reporting level to be part of the pop-up in the UI we will need to raise a separate issue on TFS, but adding it to the API endpoint is a prerequisite.
> Add reporting_level to ui_cp_poverty_charts()

- NEWS.md
- R/create_lkups.R
- data-raw/data.R
- inst/plumber/v1/endpoints.R
- tests/testthat/test-fg_pip-local.R
- tests/testthat/test-get_aux_table.R
- tests/testthat/test-pip-local.R
- tests/testthat/test-pip.R
- tests/testthat/test-ui_functions.R
- tests/testthat/test-utils-plumber.R
Make sure latest data version is available as specific folder name.
Closes #215.
> Fix latest data version

- inst/plumber/v1/endpoints.R
- tests/testthat/test-plumber-future.R
- tests/testthat/test-plumber.R
Hey - This should hopefully fix the serializer issue that causes the Stata wrapper to fail. Pushed late last night, so please review carefully :-)
> fix serializer

- DESCRIPTION
- NEWS.md
- R/create_lkups.R
- R/ui_functions.R
- man/get_pip_version.Rd
- tests/testthat/test-get_aux_table.R
- tests/testthat/test-plumber.R
- tests/testthat/test-ui_functions.R
Replaced `map` functions with apply family of functions.
> Remove purrr dependency 

- inst/plumber/v1/endpoints.R
- inst/plumber/v1/openapi.yaml
Enable new versioning options for all endpoints
> enable new versioning for all endpoints

- R/ui_functions.R
Add support for alt region to UI functions
> Add support for alt region to UI functions

- NEWS.md
- R/create_countries_vctr.R
- R/pip.R
- R/pip_grp.R
- R/pip_grp_logic.R
- R/ui_functions.R
- R/utils-plumber.R
- R/utils.R
- R/zzz.R
Fix country / region selection when using different casings
> Fix case selection

- R/create_countries_vctr.R
Hi Tony, 
This fix needs to be included urgently. It solved a problem in the aggregation of AFE and AFW, and any other aggregations. With this small fix now our estimates match the ones in the PSPR. 
Thanks. 
Best, 
@tonyfujs
> fix bug in  AFE and AFW aggregations
